import { useCallback, useEffect, useRef, useState } from 'react'

import { cancelRuntimeGeneratePullRequestFields } from '@/runtime/runtime-git-client'
import type {
  PullRequestFieldName,
  PullRequestFieldRevisions
} from '@/store/slices/pull-request-generation'

import type { SourceControlAiPrCreationDefaults } from '../../../../shared/source-control-ai-types'
import { stripBaseRef } from './create-review-base-ref'
import {
  createInitialPullRequestFieldRevisions,
  type GenerationSeed,
  type PullRequestDraftFields,
  type UseCreatePullRequestDialogFieldsOptions
} from './create-review-dialog-field-types'
import { resolveCreateReviewDraftTitle } from './create-review-draft-title'

export function useCreateReviewDialogFieldState({
  options,
  resolvedDefaultBaseRef,
  resolvedPrDefaults
}: {
  options: UseCreatePullRequestDialogFieldsOptions
  resolvedDefaultBaseRef: string
  resolvedPrDefaults: Required<SourceControlAiPrCreationDefaults>
}) {
  const { branch, eligibility, generation, open, repoId, worktreeId, worktreePath } = options
  const initializedFromEligibilityRef = useRef<string | null>(null)
  const [initializedEligibilityKey, setInitializedEligibilityKey] = useState<string | null>(null)
  const syncedDefaultBaseRef = useRef<string | null>(null)
  const baseEditedByUserRef = useRef(false)
  const autoGeneratedForKeyRef = useRef<string | null>(null)
  const generateInFlightRef = useRef(false)
  const generationRequestIdRef = useRef(0)
  const generationSeedRef = useRef<GenerationSeed | null>(null)
  const restoredExternalGenerationSeedRef = useRef<string | null>(null)
  const fieldRevisionsRef = useRef<PullRequestFieldRevisions>(
    createInitialPullRequestFieldRevisions()
  )
  const [base, setBase] = useState('')
  const [title, setTitle] = useState('')
  const [body, setBody] = useState('')
  const [draft, setDraft] = useState(false)
  const [baseQuery, setBaseQuery] = useState('')
  const [baseResults, setBaseResults] = useState<string[]>([])
  const [baseSearchError, setBaseSearchError] = useState<string | null>(null)
  const [generating, setGenerating] = useState(false)
  const [generateError, setGenerateError] = useState<string | null>(null)
  const hasExternalGeneration = Boolean(generation)
  const currentEligibilityKey =
    open && eligibility ? `${repoId}:${worktreeId ?? worktreePath}:${branch}` : null

  const markFieldDirty = useCallback((field: PullRequestFieldName): void => {
    fieldRevisionsRef.current = {
      ...fieldRevisionsRef.current,
      [field]: fieldRevisionsRef.current[field] + 1
    }
  }, [])
  const setUserBase = useCallback(
    (value: string) => {
      baseEditedByUserRef.current = true
      markFieldDirty('base')
      setBase(value)
    },
    [markFieldDirty]
  )
  const setUserTitle = useCallback(
    (value: string) => {
      markFieldDirty('title')
      setTitle(value)
    },
    [markFieldDirty]
  )
  const setUserBody = useCallback(
    (value: string) => {
      markFieldDirty('body')
      setBody(value)
    },
    [markFieldDirty]
  )
  const setUserDraft = useCallback(
    (value: boolean) => {
      markFieldDirty('draft')
      setDraft(value)
    },
    [markFieldDirty]
  )
  const applyGeneratedFields = useCallback(
    (fields: PullRequestDraftFields, seedRevisions: PullRequestFieldRevisions) => {
      const currentRevisions = fieldRevisionsRef.current
      const nextFields = { base, title, body, draft }
      // Why: asynchronous generation may only replace fields untouched since its request began.
      if (currentRevisions.base === seedRevisions.base) {
        nextFields.base = stripBaseRef(fields.base)
        setBase(nextFields.base)
        setBaseQuery('')
        setBaseResults([])
      }
      if (currentRevisions.title === seedRevisions.title) {
        nextFields.title = fields.title
        setTitle(fields.title)
      }
      if (currentRevisions.body === seedRevisions.body) {
        nextFields.body = fields.body
        setBody(fields.body)
      }
      if (currentRevisions.draft === seedRevisions.draft) {
        nextFields.draft = fields.draft
        setDraft(fields.draft)
      }
      return nextFields
    },
    [base, body, draft, title]
  )

  useEffect(() => {
    if (!open) {
      if (!hasExternalGeneration) {
        generationRequestIdRef.current += 1
        const requestContext = generationSeedRef.current?.context
        if (generateInFlightRef.current && requestContext?.worktreePath) {
          void cancelRuntimeGeneratePullRequestFields(requestContext)
        }
        generateInFlightRef.current = false
        generationSeedRef.current = null
        initializedFromEligibilityRef.current = null
        syncedDefaultBaseRef.current = null
        baseEditedByUserRef.current = false
        setInitializedEligibilityKey(null)
        autoGeneratedForKeyRef.current = null
        setGenerating(false)
        setGenerateError(null)
      }
      return
    }
    if (!eligibility || !currentEligibilityKey) {
      return
    }
    if (initializedFromEligibilityRef.current === currentEligibilityKey) {
      setInitializedEligibilityKey((current) =>
        current === currentEligibilityKey ? current : currentEligibilityKey
      )
      return
    }
    if (!hasExternalGeneration) {
      generationRequestIdRef.current += 1
      const requestContext = generationSeedRef.current?.context
      if (generateInFlightRef.current && requestContext?.worktreePath) {
        void cancelRuntimeGeneratePullRequestFields(requestContext)
      }
      generateInFlightRef.current = false
      generationSeedRef.current = null
      setGenerating(false)
    }
    initializedFromEligibilityRef.current = currentEligibilityKey
    setInitializedEligibilityKey(currentEligibilityKey)
    autoGeneratedForKeyRef.current = null
    restoredExternalGenerationSeedRef.current = null
    fieldRevisionsRef.current = createInitialPullRequestFieldRevisions()
    baseEditedByUserRef.current = false
    syncedDefaultBaseRef.current = resolvedDefaultBaseRef || null
    setBase(resolvedDefaultBaseRef)
    setTitle(resolveCreateReviewDraftTitle({ branch, eligibilityTitle: eligibility.title }))
    setBody(eligibility.body ?? '')
    setDraft(resolvedPrDefaults.draft)
    setBaseQuery('')
    setBaseResults([])
    setBaseSearchError(null)
    setGenerateError(null)
  }, [
    branch,
    currentEligibilityKey,
    eligibility,
    hasExternalGeneration,
    open,
    resolvedDefaultBaseRef,
    resolvedPrDefaults.draft
  ])

  const externalGenerationSeedRestoreKey = generation?.seedRestoreKey
  const externalGenerationSeed = generation?.seed
  const externalGenerationSeedFieldRevisions = generation?.seedFieldRevisions
  const onExternalGenerationSeedRestored = generation?.onSeedRestored

  useEffect(() => {
    if (
      !open ||
      !externalGenerationSeedRestoreKey ||
      !externalGenerationSeed ||
      !externalGenerationSeedFieldRevisions ||
      !initializedFromEligibilityRef.current ||
      restoredExternalGenerationSeedRef.current === externalGenerationSeedRestoreKey
    ) {
      return
    }
    // Why: external generation survives unmounts, so restore its revision guards with its seed.
    restoredExternalGenerationSeedRef.current = externalGenerationSeedRestoreKey
    fieldRevisionsRef.current = { ...externalGenerationSeedFieldRevisions }
    baseEditedByUserRef.current = true
    setBase(stripBaseRef(externalGenerationSeed.base))
    setTitle(externalGenerationSeed.title)
    setBody(externalGenerationSeed.body)
    setDraft(externalGenerationSeed.draft)
    setBaseQuery('')
    setBaseResults([])
    setBaseSearchError(null)
    onExternalGenerationSeedRestored?.(externalGenerationSeedRestoreKey)
  }, [
    externalGenerationSeed,
    externalGenerationSeedFieldRevisions,
    externalGenerationSeedRestoreKey,
    onExternalGenerationSeedRestored,
    open
  ])

  useEffect(() => {
    if (
      !open ||
      !eligibility ||
      !initializedFromEligibilityRef.current ||
      !resolvedDefaultBaseRef
    ) {
      return
    }
    if (syncedDefaultBaseRef.current === resolvedDefaultBaseRef) {
      return
    }
    syncedDefaultBaseRef.current = resolvedDefaultBaseRef
    if (baseEditedByUserRef.current) {
      return
    }
    markFieldDirty('base')
    setBase(resolvedDefaultBaseRef)
    setBaseQuery('')
    setBaseResults([])
    setBaseSearchError(null)
  }, [eligibility, markFieldDirty, open, resolvedDefaultBaseRef])

  return {
    applyGeneratedFields,
    autoGeneratedForKeyRef,
    base,
    baseQuery,
    baseResults,
    baseSearchError,
    body,
    currentEligibilityKey,
    draft,
    fieldRevisionsRef,
    generateError,
    generateInFlightRef,
    generating,
    generationRequestIdRef,
    generationSeedRef,
    initializedEligibilityKey,
    initializedFromEligibilityRef,
    setBase,
    setBaseQuery,
    setBaseResults,
    setBaseSearchError,
    setBody: setUserBody,
    setDraft: setUserDraft,
    setGenerateError,
    setGenerating,
    setTitle: setUserTitle,
    setUserBase,
    title
  }
}

export type CreateReviewDialogFieldState = ReturnType<typeof useCreateReviewDialogFieldState>
