export {
  buildAgentFeatureSkillInstallCommand,
  buildAgentFeatureSkillUpdateCommand,
  COMPUTER_USE_SKILL_INSTALL_COMMAND,
  COMPUTER_USE_SKILL_NAME,
  COMPUTER_USE_SKILL_UPDATE_COMMAND,
  EPHEMERAL_VMS_SKILL_INSTALL_COMMAND,
  EPHEMERAL_VMS_SKILL_NAME,
  EPHEMERAL_VMS_SKILL_UPDATE_COMMAND,
  YIRU_CLI_SKILL_INSTALL_COMMAND,
  YIRU_CLI_ORCHESTRATION_SKILL_INSTALL_COMMAND,
  YIRU_CLI_SKILL_NAME,
  YIRU_CLI_SKILL_UPDATE_COMMAND,
  ORCHESTRATION_SKILL_NAME,
  ORCHESTRATION_SKILL_UPDATE_COMMAND
} from '../../../shared/agent-feature-install-commands'
