// Why: the auto-generated workspace name pool lives in shared (not renderer)
// so the main process can recognize a Yiru-generated branch name when deciding
// whether auto-rename-from-work is allowed to overwrite it.
export const MARINE_CREATURES = [
  ...(['Nautilus', 'Seahorse', 'Starfish', 'Coral', 'Narwhal', 'Jellyfish'] as const),
  ...(['Octopus', 'Manta', 'Dolphin', 'Manatee', 'Cuttlefish', 'Anemone', 'Urchin'] as const),
  ...(['Triton', 'Nudibranch', 'Coelacanth', 'Oarfish', 'Beluga', 'Dugong'] as const),
  ...(['Porpoise', 'Stingray', 'Hammerhead', 'Wobbegong', 'Sawfish', 'Chimaera'] as const),
  ...(['Anglerfish', 'Viperfish', 'Dragonfish', 'Axolotl', 'Otter', 'Seadragon'] as const),
  ...(['Seahare', 'Squid', 'Argonaut', 'Sponge', 'Barnacle', 'Cowrie', 'Guitarfish'] as const),
  ...(['Lamprey', 'Isopod', 'Lionfish', 'Clownfish', 'Angelfish', 'Butterflyfish'] as const),
  ...(['Parrotfish', 'Pufferfish', 'Moonfish', 'Firefish', 'Unicornfish'] as const),
  ...(['Rainbowfish', 'Betta', 'Discus', 'Arowana', 'Koi', 'Piranha', 'Barracuda'] as const),
  ...(['Moray', 'Sunfish', 'Lanternfish', 'Archerfish', 'Mudskipper', 'Hatchetfish'] as const),
  ...(['Knifefish', 'Leaffish', 'Glassfish', 'Ropefish', 'Bichir', 'Tigerfish'] as const),
  ...(['Cardinalfish', 'Lungfish', 'Opah', 'Frogfish', 'Stonefish', 'Cutlassfish'] as const),
  ...(['Paddlefish', 'Arapaima', 'Mandarin', 'Blobfish', 'Thresher', 'Vaquita'] as const),
  ...(['Pipefish', 'Guppy', 'Tetra', 'Danio', 'Cichlid', 'Oscar', 'Gourami'] as const),
  ...(['Killifish', 'Rasbora', 'Pleco', 'Goldfish', 'Molly', 'Platy', 'Barb'] as const),
  ...(['Loach', 'Medaka', 'Pacu', 'Filefish', 'Boxfish', 'Cowfish', 'Surgeonfish'] as const),
  ...(['Damselfish', 'Wrasse', 'Goby', 'Blenny', 'Conger', 'Sculpin', 'Darter'] as const),
  ...(['Remora', 'Pilotfish', 'Trumpetfish', 'Cornetfish', 'Jawfish', 'Toadfish'] as const),
  ...(['Pearlfish', 'Driftfish', 'Lumpfish', 'Snailfish', 'Stickleback', 'Halfbeak'] as const),
  ...(['Snipefish', 'Pencilfish', 'Snakehead', 'Tripletail', 'Lookdown', 'Sweetlips'] as const),
  ...(['Squirrelfish', 'Soldierfish', 'Rabbitfish', 'Hawkfish', 'Bannerfish'] as const),
  ...(['Batfish', 'Chromis', 'Anthias', 'Fusilier', 'Sweeper', 'Emperor', 'Ponyfish'] as const),
  ...(['Kelpfish', 'Weever', 'Pearlside', 'Opaleye', 'Ballyhoo', 'Needlefish'] as const),
  ...(['Triggerfish', 'Gar', 'Tarpon', 'Sailfish', 'Conch', 'Walrus', 'Seal'] as const),
  ...(['Penguin', 'Hagfish', 'Gulper', 'Hydra', 'Krill', 'Salp', 'Tunicate'] as const),
  ...(['Crinoid', 'Polyp', 'Limpet', 'Whelk', 'Bowfin', 'Minnow', 'Gudgeon'] as const),
  ...(['Goldeye', 'Mooneye', 'Soapfish', 'Leatherjacket', 'Rudderfish', 'Sabrefish'] as const),
  ...(['Puffin', 'Albatross', 'Osprey', 'Pelican', 'Petrel', 'Gannet', 'Tern'] as const),
  ...(['Cormorant', 'Leatherback', 'Hawksbill', 'Loggerhead', 'Dottyback', 'Basslet'] as const),
  ...(['Gramma', 'Hamlet', 'Hogfish', 'Dartfish', 'Foxface', 'Shrimpfish'] as const),
  ...(['Pyrosome', 'Seapen', 'Medusa', 'Candlefish', 'Silverside', 'Shiner'] as const),
  ...(['Eelpout', 'Madtom', 'Shovelnose', 'Sandlance', 'Tubesnout', 'Marlin'] as const),
  ...(['Bonefish', 'Dace', 'Rudd', 'Spirula', 'Permit', 'Grunt', 'Trevally'] as const),
  ...(['Croaker', 'Drum', 'Ladyfish', 'Bullhead', 'Torpedo', 'Skate', 'Hermit'] as const),
  ...(['Fiddler', 'Fireworm', 'Tubeworm', 'Amphipod', 'Copepod', 'Pteropod'] as const),
  ...(['Seaslug', 'Swordtail', 'Bluegill', 'Pickerel', 'Redhorse', 'Logperch'] as const),
  ...(['Goblin', 'Catshark', 'Harlequin', 'Murex', 'Volute', 'Wentletrap', 'Nerite'] as const),
  ...(['Stargazer', 'Handfish', 'Flyingfish', 'Waspfish', 'Skua', 'Shearwater'] as const),
  ...(['Guillemot', 'Razorbill', 'Auk', 'Fulmar', 'Murre', 'Velvetfish', 'Prowfish'] as const),
  ...(['Sandperch', 'Bobtail', 'Chiton', 'Featherstar', 'Nereid', 'Siren', 'Kraken'] as const),
  ...(['Selkie', 'Leviathan', 'Wolffish', 'Wreckfish', 'Horseshoe', 'Cachalot'] as const),
  ...(['Rorqual', 'Grampus', 'Humpback', 'Bowhead', 'Finback', 'Sealion', 'Pinniped'] as const),
  ...(['Cetacean', 'Mako', 'Porbeagle', 'Dogfish', 'Spurdog', 'Tope', 'Bonnethead'] as const),
  ...(['Sixgill', 'Sevengill', 'Angelshark', 'Houndshark', 'Megamouth'] as const),
  ...(['Cookiecutter', 'Bramble', 'Ghostshark', 'Sandtiger', 'Galeocerdo'] as const),
  ...(['Nursehound', 'Cownose', 'Devilray', 'Eagleray', 'Butterflyray', 'Numbfish'] as const),
  ...(['Stingaree', 'Mantaray', 'Tuna', 'Albacore', 'Bonito', 'Skipjack', 'Wahoo'] as const),
  ...(['Kingfish', 'Mackerel', 'Cero', 'Dorado', 'Mahimahi', 'Escolar', 'Pomfret'] as const),
  ...(['Butterfish', 'Cod', 'Haddock', 'Pollock', 'Whiting', 'Hake', 'Ling', 'Cusk'] as const),
  ...(['Burbot', 'Saithe', 'Sablefish', 'Lingcod', 'Greenling', 'Rockling'] as const),
  ...(['Halibut', 'Flounder', 'Sole', 'Plaice', 'Turbot', 'Brill', 'Dab', 'Fluke'] as const),
  ...(['Megrim', 'Sanddab', 'Herring', 'Sardine', 'Anchovy', 'Sprat', 'Pilchard'] as const),
  ...(['Menhaden', 'Shad', 'Alewife', 'Salmon', 'Trout', 'Char', 'Grayling'] as const),
  ...(['Steelhead', 'Kokanee', 'Chinook', 'Coho', 'Sockeye', 'Taimen', 'Huchen'] as const),
  ...(['Cisco', 'Inconnu', 'Vendace', 'Whitefish', 'Perch', 'Bass', 'Snapper'] as const),
  ...(['Grouper', 'Seabass', 'Tilefish', 'Bream', 'Porgy', 'Sheepshead', 'Pinfish'] as const),
  ...(['Scup', 'Tautog', 'Sander', 'Zander', 'Walleye', 'Sauger', 'Ruffe', 'Comber'] as const),
  ...(['Hind', 'Coney', 'Graysby', 'Margate', 'Pompano', 'Amberjack', 'Yellowtail'] as const),
  ...(['Scad', 'Runner', 'Mullet', 'Goatfish', 'Threadfin', 'Snook', 'Barramundi'] as const),
  ...(['Milkfish', 'Mojarra', 'Weakfish', 'Corbina', 'Queenfish', 'Kahawai'] as const),
  ...(['Tilapia', 'Cunner', 'Tuskfish', 'Razorfish', 'Tang', 'Porcupinefish'] as const),
  ...(['Burrfish', 'Eel', 'Wolfeel', 'Gardeneel', 'Ribboneel', 'Cuskeel', 'Catfish'] as const),
  ...(['Cory', 'Ratfish', 'Elephantfish', 'Goosefish', 'Monkfish', 'Sargassum'] as const),
  ...(['Coffinfish', 'Seadevil', 'Scorpionfish', 'Rockfish', 'Cabezon', 'Rosefish'] as const),
  ...(['Redfish', 'Bocaccio', 'Thornyhead', 'Gurnard', 'Searobin', 'Fangtooth'] as const),
  ...(['Bristlemouth', 'Barreleye', 'Spookfish', 'Telescopefish', 'Lancetfish'] as const),
  ...(['Tripodfish', 'Spiderfish', 'Daggertooth', 'Pearleye', 'Ridgehead'] as const),
  ...(['Snaggletooth', 'Sturgeon', 'Sterlet', 'Kaluga', 'Cockle', 'Mussel', 'Clam'] as const),
  ...(['Oyster', 'Scallop', 'Abalone', 'Periwinkle', 'Cerith', 'Turban', 'Tellin'] as const),
  ...(['Geoduck', 'Quahog', 'Piddock', 'Shipworm', 'Lobster', 'Crayfish', 'Shrimp'] as const),
  ...(['Prawn', 'Langostino', 'Langouste', 'Yabby', 'Marron', 'Dungeness', 'Seafan'] as const),
  ...(['Staghorn', 'Elkhorn', 'Hydroid', 'Zoanthid', 'Gorgonian', 'Seanettle'] as const),
  ...(['Moonjelly', 'Sanddollar', 'Brittlestar', 'Basketstar', 'Sunstar'] as const),
  ...(['Seacucumber', 'Seabiscuit', 'Hearturchin', 'Bristleworm', 'Featherduster'] as const),
  ...(['Lugworm', 'Sandworm', 'Palolo', 'Arrowworm', 'Acornworm', 'Flatworm'] as const),
  ...(['Ribbonworm', 'Booby', 'Frigatebird', 'Tropicbird', 'Noddy', 'Kittiwake'] as const),
  ...(['Dovekie', 'Shag', 'Anhinga', 'Skimmer', 'Jaeger', 'Oystercatcher', 'Eider'] as const),
  ...(['Scoter', 'Merganser', 'Brant', 'Ridley', 'Flatback', 'Terrapin', 'Seasnake'] as const),
  ...(['Diatom', 'Plankton', 'Larvacean', 'Doliolid', 'Kelp', 'Seagrass', 'Eelgrass'] as const),
  ...(['Dulse', 'Bladderwrack', 'Mola', 'Scylla', 'Charybdis', 'Cetus', 'Proteus'] as const),
  ...(['Glaucus', 'Hippocamp', 'Jormungandr', 'Hafgufa', 'Kelpie', 'Merrow'] as const),
  ...(['Nuckelavee', 'Afanc', 'Rusalka', 'Vodyanoy', 'Umibozu', 'Isonade', 'Ningyo'] as const),
  ...(['Mizuchi', 'Naga', 'Makara', 'Bunyip', 'Taniwha', 'Marakihau', 'Lusca'] as const),
  ...(['Undine', 'Nixie', 'Melusine', 'Ondine', 'Tiamat', 'Dagon', 'Aspidochelone'] as const),
  ...(['Capricorn', 'Merfolk', 'Merman', 'Mermaid', 'Timingila', 'Bakekujira'] as const),
  ...(['Jiaolong', 'Encantado', 'Hraesvelg'] as const)
] as const
