allowBuilds:
  esbuild: true

overrides:
  xcode>uuid: 11.1.1
  vite: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
