export function getOpenCodePluginSource(): string {
  return getOpenCodeFamilyPluginSource('/hook/opencode')
}

export function getOpenCodeFamilyPluginSource(hookPathname: string): string {
  // Why: this artifact executes in OpenCode's Node process, where it cannot
  // import Yiru modules; keep the emitted plugin self-contained.
  return [
    'let warnedBadEndpoint = false;',
    'let cachedEndpointKey = "";',
    'let cachedEndpointValues = null;',
    '',
    'function readEndpointFile() {',
    '  const path = process.env.YIRU_AGENT_HOOK_ENDPOINT;',
    '  if (!path) return null;',
    '  try {',
    '    const fs = require("fs");',
    '    try {',
    '      const stat = fs.statSync(path);',
    '      const cacheKey = stat.mtimeMs + ":" + stat.size + ":" + stat.ino;',
    '      if (cacheKey === cachedEndpointKey && cachedEndpointValues) {',
    '        return cachedEndpointValues;',
    '      }',
    '      const contents = fs.readFileSync(path, "utf8");',
    '      const out = {};',
    '      for (const line of contents.split(/\\r?\\n/)) {',
    '        const m = line.match(/^(?:set\\s+)?([A-Z0-9_]+)=(.*)$/);',
    '        if (m) out[m[1]] = m[2].replace(/\\r$/, "");',
    '      }',
    '      cachedEndpointKey = cacheKey;',
    '      cachedEndpointValues = out;',
    '      return out;',
    '    } catch (ioErr) {',
    '      cachedEndpointKey = "";',
    '      cachedEndpointValues = null;',
    '      throw ioErr;',
    '    }',
    '  } catch (err) {',
    '    if (err && err.code !== "ENOENT" && !warnedBadEndpoint) {',
    '      warnedBadEndpoint = true;',
    '      console.warn("[yiru-hook] failed to parse endpoint file:", err.message);',
    '    }',
    '    return null;',
    '  }',
    '}',
    '',
    'function resolveHookCoords() {',
    '  const fileEnv = readEndpointFile() || {};',
    '  return {',
    '    port: fileEnv.YIRU_AGENT_HOOK_PORT || process.env.YIRU_AGENT_HOOK_PORT,',
    '    token: fileEnv.YIRU_AGENT_HOOK_TOKEN || process.env.YIRU_AGENT_HOOK_TOKEN,',
    '    env: fileEnv.YIRU_AGENT_HOOK_ENV || process.env.YIRU_AGENT_HOOK_ENV || "",',
    '    version: fileEnv.YIRU_AGENT_HOOK_VERSION || process.env.YIRU_AGENT_HOOK_VERSION || "",',
    '  };',
    '}',
    '',
    'function getStatusType(event) {',
    '  return event?.properties?.status?.type ?? event?.status?.type ?? null;',
    '}',
    '',
    'let lastStatus = "idle";',
    'const childSessionById = new Map();',
    'const MESSAGE_PART_THROTTLE_MS = 250;',
    'const MESSAGE_PART_MAX_CHARS = 4000;',
    'let pendingAssistantPart = null;',
    'let assistantPartFlushTimer = null;',
    'let lastAssistantPartPostAt = 0;',
    '',
    'function capMessagePartText(text) {',
    '  return text.length > MESSAGE_PART_MAX_CHARS ? text.slice(0, MESSAGE_PART_MAX_CHARS) : text;',
    '}',
    '',
    'async function flushPendingAssistantPart() {',
    '  if (assistantPartFlushTimer) {',
    '    clearTimeout(assistantPartFlushTimer);',
    '    assistantPartFlushTimer = null;',
    '  }',
    '  const pending = pendingAssistantPart;',
    '  pendingAssistantPart = null;',
    '  if (!pending) return;',
    '  lastAssistantPartPostAt = Date.now();',
    '  await post("MessagePart", {',
    '    role: pending.role,',
    '    text: capMessagePartText(pending.text),',
    '    messageID: pending.messageID,',
    '    sessionID: pending.sessionID,',
    '  });',
    '}',
    '',
    'function queueAssistantPart(part) {',
    '  pendingAssistantPart = part;',
    '  const sinceLastPost = Date.now() - lastAssistantPartPostAt;',
    '  if (sinceLastPost >= MESSAGE_PART_THROTTLE_MS) {',
    '    void flushPendingAssistantPart();',
    '    return;',
    '  }',
    '  if (!assistantPartFlushTimer) {',
    '    assistantPartFlushTimer = setTimeout(() => {',
    '      void flushPendingAssistantPart();',
    '    }, MESSAGE_PART_THROTTLE_MS - sinceLastPost);',
    '    if (assistantPartFlushTimer.unref) assistantPartFlushTimer.unref();',
    '  }',
    '}',
    '',
    'const messageRoleById = new Map();',
    'function rememberMessageRole(messageID, role) {',
    '  if (!messageID || !role) return;',
    '  if (messageRoleById.size >= 128) {',
    '    const first = messageRoleById.keys().next().value;',
    '    if (first !== undefined) messageRoleById.delete(first);',
    '  }',
    '  messageRoleById.set(messageID, role);',
    '}',
    '',
    'async function isChildSession(client, sessionID) {',
    '  if (!sessionID) return true;',
    '  if (childSessionById.has(sessionID)) return childSessionById.get(sessionID);',
    '  if (!client?.session?.list) return true;',
    '  try {',
    '    const sessions = await client.session.list();',
    '    const list = Array.isArray(sessions?.data) ? sessions.data : [];',
    '    const session = list.find((entry) => entry?.id === sessionID);',
    '    const isChild = !!session?.parentID;',
    '    if (childSessionById.size >= 128) {',
    '      const first = childSessionById.keys().next().value;',
    '      if (first !== undefined) childSessionById.delete(first);',
    '    }',
    '    childSessionById.set(sessionID, isChild);',
    '    return isChild;',
    '  } catch {',
    '    return true;',
    '  }',
    '}',
    '',
    'async function post(hookEventName, extraProperties) {',
    '  const coords = resolveHookCoords();',
    '  const paneKey = process.env.YIRU_PANE_KEY;',
    '  if (!coords.port || !coords.token || !paneKey) return;',
    `  const url = \`http://127.0.0.1:\${coords.port}${hookPathname}\`;`,
    '  const body = JSON.stringify({',
    '    paneKey,',
    '    launchToken: process.env.YIRU_AGENT_LAUNCH_TOKEN || "",',
    '    tabId: process.env.YIRU_TAB_ID || "",',
    '    worktreeId: process.env.YIRU_WORKTREE_ID || "",',
    '    env: coords.env,',
    '    version: coords.version,',
    '    payload: { hook_event_name: hookEventName, ...(extraProperties || {}) },',
    '  });',
    '  try {',
    '    await fetch(url, {',
    '      method: "POST",',
    '      headers: {',
    '        "Content-Type": "application/json",',
    '        "X-Yiru-Agent-Hook-Token": coords.token,',
    '      },',
    '      body,',
    '    });',
    '  } catch {',
    '  }',
    '}',
    '',
    'async function setStatus(next, extraProperties) {',
    '  if (lastStatus === next) return;',
    '  lastStatus = next;',
    '  const hookEventName = next === "busy" ? "SessionBusy" : "SessionIdle";',
    '  await post(hookEventName, extraProperties);',
    '}',
    '',
    'export const YiruOpenCodeStatusPlugin = async (_ctx) => {',
    '  const client = _ctx?.client;',
    '  return {',
    '  event: async ({ event }) => {',
    '    if (!event?.type) return;',
    '    if (event.type === "message.updated") {',
    '      const info = event.properties && event.properties.info;',
    '      rememberMessageRole(info && info.id, info && info.role);',
    '    }',
    '    const sessionID = event.properties?.sessionID;',
    '    if (sessionID && (await isChildSession(client, sessionID))) {',
    '      return;',
    '    }',
    '    if (event.type === "permission.asked") {',
    '      await post("PermissionRequest", event.properties || {});',
    '      return;',
    '    }',
    '    if (event.type === "question.asked") {',
    '      await post("AskUserQuestion", event.properties || {});',
    '      return;',
    '    }',
    '    if (event.type === "message.updated") {',
    '      return;',
    '    }',
    '    if (event.type === "message.part.updated") {',
    '      const part = event.properties && event.properties.part;',
    '      if (!part || part.type !== "text" || !part.text) return;',
    '      const role = messageRoleById.get(part.messageID);',
    '      if (!role) return;',
    '      if (role === "user") {',
    '        await post("MessagePart", { role, text: capMessagePartText(part.text), messageID: part.messageID, sessionID });',
    '        return;',
    '      }',
    '      queueAssistantPart({ role, text: part.text, messageID: part.messageID, sessionID });',
    '      return;',
    '    }',
    '    if (event.type === "session.idle" || event.type === "session.error") {',
    '      await flushPendingAssistantPart();',
    '      await setStatus("idle", { sessionID });',
    '      return;',
    '    }',
    '    if (event.type === "session.status") {',
    '      const statusType = getStatusType(event);',
    '      if (statusType === "busy" || statusType === "retry") {',
    '        await setStatus("busy", { sessionID });',
    '        return;',
    '      }',
    '      if (statusType === "idle") {',
    '        await setStatus("idle", { sessionID });',
    '      }',
    '    }',
    '  },',
    '  };',
    '};',
    ''
  ].join('\n')
}
