import type { resolveSourceControlAiForOperation } from '@yiru/runtime-protocol/workbench/source-control/ai'
import type { SourceControlAiPrCreationDefaults } from '@yiru/runtime-protocol/workbench/source-control/ai-types'
import { useEffect } from 'react'
import { useEventCallback } from '~renderer/react/use-event-callback'
import { getConnectionId } from '~renderer/runtime/connection-context'
import {
  cancelRuntimeGeneratePullRequestFields,
  generateRuntimePullRequestFields,
  type RuntimeGeneratePullRequestFieldsOverrides
} from '~renderer/runtime/git-client'
import { useAppStore } from '~renderer/store/state'

import { stripBaseRef } from './create-review-base-ref'
import type { CreateReviewDialogFieldState } from './create-review-dialog-field-state'
import type { UseCreatePullRequestDialogFieldsOptions } from './create-review-dialog-field-types'

export function useCreateReviewFieldGeneration({
  options,
  resolvedPullRequestAi,
  resolvedPrDefaults,
  state
}: {
  options: UseCreatePullRequestDialogFieldsOptions
  resolvedPullRequestAi: ReturnType<typeof resolveSourceControlAiForOperation> | null
  resolvedPrDefaults: Required<SourceControlAiPrCreationDefaults>
  state: CreateReviewDialogFieldState
}) {
  const {
    eligibility,
    generation,
    onBranchChangedByGeneration,
    open,
    settings,
    submitting,
    worktreeId,
    worktreePath
  } = options
  const {
    applyGeneratedFields,
    autoGeneratedForKeyRef,
    base,
    body,
    draft,
    fieldRevisionsRef,
    generateError,
    generateInFlightRef,
    generating,
    generationRequestIdRef,
    generationSeedRef,
    initializedFromEligibilityRef,
    setGenerateError,
    setGenerating,
    title
  } = state
  const effectiveGenerating = generation?.generating ?? generating
  const effectiveGenerateError = generation?.generateError ?? generateError
  let generateDisabledReason: string | undefined
  if (submitting) {
    generateDisabledReason = 'Create PR in progress...'
  } else if (!resolvedPullRequestAi?.ok) {
    generateDisabledReason =
      resolvedPullRequestAi?.error ?? 'Enable Source Control AI in Settings -> Git.'
  } else if (!base.trim()) {
    generateDisabledReason = 'Choose a base branch before generating.'
  }
  const generateDisabled = !effectiveGenerating && Boolean(generateDisabledReason)

  const handleGenerate = useEventCallback(
    async (overrides?: RuntimeGeneratePullRequestFieldsOverrides): Promise<void> => {
      if (!worktreePath || !base.trim() || effectiveGenerating || generateDisabled) {
        return
      }
      if (generation) {
        generation.onGenerate(
          { base, title, body, draft },
          { ...fieldRevisionsRef.current },
          overrides
        )
        return
      }
      const requestId = generationRequestIdRef.current + 1
      generationRequestIdRef.current = requestId
      const requestContext = {
        // Why: generation stays pinned to the visible worktree owner across host changes.
        settings,
        worktreeId,
        worktreePath,
        connectionId: getConnectionId(worktreeId) ?? undefined
      }
      generationSeedRef.current = {
        requestId,
        fieldRevisions: { ...fieldRevisionsRef.current },
        context: requestContext
      }
      generateInFlightRef.current = true
      setGenerating(true)
      setGenerateError(null)
      try {
        const result = await generateRuntimePullRequestFields(
          requestContext,
          {
            base: stripBaseRef(base.trim()),
            title,
            body,
            draft,
            provider: eligibility?.provider,
            useTemplate: resolvedPrDefaults.useTemplate
          },
          overrides
        )
        if (result.branchChangedByPreparation) {
          await onBranchChangedByGeneration?.()
        }
        if (generationRequestIdRef.current !== requestId) {
          return
        }
        if (!result.success) {
          setGenerateError(result.canceled ? null : result.error)
          return
        }
        const currentSeed = generationSeedRef.current
        if (!currentSeed || currentSeed.requestId !== requestId) {
          return
        }
        applyGeneratedFields(result.fields, currentSeed.fieldRevisions)
        useAppStore.getState().recordFeatureInteraction('ai-pr-generation')
        setGenerateError(null)
      } catch (error) {
        if (generationRequestIdRef.current === requestId) {
          setGenerateError(
            error instanceof Error ? error.message : 'Failed to generate pull request details'
          )
        }
      } finally {
        if (generationRequestIdRef.current === requestId) {
          generateInFlightRef.current = false
          generationSeedRef.current = null
          setGenerating(false)
        }
      }
    }
  )

  const handleCancelGenerate = (): void => {
    if (generation) {
      generation.onCancelGenerate()
      return
    }
    const requestContext = generationSeedRef.current?.context
    if (!requestContext?.worktreePath || !generateInFlightRef.current) {
      return
    }
    generationRequestIdRef.current += 1
    generateInFlightRef.current = false
    generationSeedRef.current = null
    setGenerating(false)
    setGenerateError(null)
    void cancelRuntimeGeneratePullRequestFields(requestContext)
  }

  useEffect(() => {
    if (
      !open ||
      !resolvedPrDefaults.generateDetailsOnOpen ||
      !initializedFromEligibilityRef.current ||
      autoGeneratedForKeyRef.current === initializedFromEligibilityRef.current ||
      generateDisabled ||
      effectiveGenerating ||
      !base.trim()
    ) {
      return
    }
    autoGeneratedForKeyRef.current = initializedFromEligibilityRef.current
    void handleGenerate()
  }, [
    autoGeneratedForKeyRef,
    base,
    effectiveGenerating,
    generateDisabled,
    handleGenerate,
    initializedFromEligibilityRef,
    open,
    resolvedPrDefaults.generateDetailsOnOpen
  ])

  return {
    effectiveGenerateError,
    effectiveGenerating,
    generateDisabled,
    generateDisabledReason,
    handleCancelGenerate,
    handleGenerate
  }
}
