import type { SourceControlAiPrCreationDefaults } from '@yiru/runtime-protocol/workbench/source-control/ai-types'
import { useEffect, useRef, useState } from 'react'
import { useEventCallback } from '~renderer/react/use-event-callback'
import { cancelRuntimeGeneratePullRequestFields } from '~renderer/runtime/git-client'
import type {
  PullRequestFieldName,
  PullRequestFieldRevisions
} from '~renderer/workspace-panel/pull-request-generation-state'

import { stripBaseRef } from './create-review-base-ref'
import {
  createInitialPullRequestFieldRevisions,
  type GenerationSeed,
  type PullRequestDraftFields,
  type UseCreatePullRequestDialogFieldsOptions
} from './create-review-dialog-field-types'
import { resolveCreateReviewDraftTitle } from './create-review-draft-title'

type TaggedGenerateError = {
  key: string
  message: string
}

export function useCreateReviewDialogFieldState({
  options,
  resolvedDefaultBaseRef,
  resolvedPrDefaults
}: {
  options: UseCreatePullRequestDialogFieldsOptions
  resolvedDefaultBaseRef: string
  resolvedPrDefaults: Required<SourceControlAiPrCreationDefaults>
}) {
  const { branch, eligibility, generation, open, repoId, worktreeId, worktreePath } = options
  const initializedFromEligibilityRef = useRef<string | null>(null)
  const syncedDefaultBaseRef = useRef<string | null>(null)
  const baseEditedByUserRef = useRef(false)
  const autoGeneratedForKeyRef = useRef<string | null>(null)
  const generateInFlightRef = useRef(false)
  const generationRequestIdRef = useRef(0)
  const generationSeedRef = useRef<GenerationSeed | null>(null)
  const restoredExternalGenerationSeedRef = useRef<string | null>(null)
  const fieldRevisionsRef = useRef<PullRequestFieldRevisions>(
    createInitialPullRequestFieldRevisions()
  )
  // Why: a base-ref typeahead session belongs to whichever base was last
  // committed programmatically. Bumping this epoch instead of clearing
  // query/results/error inline inside each reset effect lets one render-time
  // comparison below clear all three atomically, in the same commit as the
  // base reset — there is no follow-up frame where the query has cleared but
  // the results list still shows a previous target's matches.
  const baseSearchEpochRef = useRef(0)
  const clearedBaseSearchEpochRef = useRef(0)
  const [base, setBase] = useState('')
  const [title, setTitle] = useState('')
  const [body, setBody] = useState('')
  const [draft, setDraft] = useState(false)
  const [baseQuery, setBaseQuery] = useState('')
  const [baseResults, setBaseResults] = useState<string[]>([])
  const [baseSearchError, setBaseSearchError] = useState<string | null>(null)
  const [inFlightGenerationKey, setInFlightGenerationKey] = useState<string | null>(null)
  const [taggedGenerateError, setTaggedGenerateError] = useState<TaggedGenerateError | null>(null)
  const hasExternalGeneration = Boolean(generation)
  const currentEligibilityKey =
    open && eligibility ? `${repoId}:${worktreeId ?? worktreePath}:${branch}` : null
  // Why: mirrors initializedFromEligibilityRef, which the effect below already
  // maintains — deriving it here avoids a second state slot that could drift.
  const initializedEligibilityKey =
    initializedFromEligibilityRef.current === currentEligibilityKey ? currentEligibilityKey : null
  // Why: generating/generateError are tagged by the eligibility key that
  // started them rather than cleared explicitly on close/reinit — an old tag
  // stops matching the new key by itself, so no synchronous setter call is
  // needed inside the reset effects below to hide a stale in-flight flag or
  // error message.
  const generating =
    inFlightGenerationKey !== null && inFlightGenerationKey === currentEligibilityKey
  const generateError =
    taggedGenerateError && taggedGenerateError.key === currentEligibilityKey
      ? taggedGenerateError.message
      : null

  const markFieldDirty = (field: PullRequestFieldName): void => {
    fieldRevisionsRef.current = {
      ...fieldRevisionsRef.current,
      [field]: fieldRevisionsRef.current[field] + 1
    }
  }
  const invalidateBaseSearch = useEventCallback((): void => {
    baseSearchEpochRef.current += 1
  })
  const setUserBase = (value: string) => {
    baseEditedByUserRef.current = true
    markFieldDirty('base')
    setBase(value)
  }
  const setUserTitle = (value: string) => {
    markFieldDirty('title')
    setTitle(value)
  }
  const setUserBody = (value: string) => {
    markFieldDirty('body')
    setBody(value)
  }
  const setUserDraft = (value: boolean) => {
    markFieldDirty('draft')
    setDraft(value)
  }
  const setGenerating = (value: boolean) => {
    setInFlightGenerationKey(value ? currentEligibilityKey : null)
  }
  const setGenerateError = (message: string | null) => {
    setTaggedGenerateError(
      message === null || currentEligibilityKey === null
        ? null
        : { key: currentEligibilityKey, message }
    )
  }
  const applyGeneratedFields = (
    fields: PullRequestDraftFields,
    seedRevisions: PullRequestFieldRevisions
  ) => {
    const currentRevisions = fieldRevisionsRef.current
    const nextFields = { base, title, body, draft }
    // Why: asynchronous generation may only replace fields untouched since its request began.
    if (currentRevisions.base === seedRevisions.base) {
      nextFields.base = stripBaseRef(fields.base)
      setBase(nextFields.base)
      invalidateBaseSearch()
    }
    if (currentRevisions.title === seedRevisions.title) {
      nextFields.title = fields.title
      setTitle(fields.title)
    }
    if (currentRevisions.body === seedRevisions.body) {
      nextFields.body = fields.body
      setBody(fields.body)
    }
    if (currentRevisions.draft === seedRevisions.draft) {
      nextFields.draft = fields.draft
      setDraft(fields.draft)
    }
    return nextFields
  }

  useEffect(() => {
    if (!open) {
      if (!hasExternalGeneration) {
        generationRequestIdRef.current += 1
        const requestContext = generationSeedRef.current?.context
        if (generateInFlightRef.current && requestContext?.worktreePath) {
          void cancelRuntimeGeneratePullRequestFields(requestContext)
        }
        generateInFlightRef.current = false
        generationSeedRef.current = null
        initializedFromEligibilityRef.current = null
        syncedDefaultBaseRef.current = null
        baseEditedByUserRef.current = false
        autoGeneratedForKeyRef.current = null
      }
      return
    }
    if (!eligibility || !currentEligibilityKey) {
      return
    }
    if (initializedFromEligibilityRef.current === currentEligibilityKey) {
      return
    }
    if (!hasExternalGeneration) {
      generationRequestIdRef.current += 1
      const requestContext = generationSeedRef.current?.context
      if (generateInFlightRef.current && requestContext?.worktreePath) {
        void cancelRuntimeGeneratePullRequestFields(requestContext)
      }
      generateInFlightRef.current = false
      generationSeedRef.current = null
    }
    initializedFromEligibilityRef.current = currentEligibilityKey
    autoGeneratedForKeyRef.current = null
    restoredExternalGenerationSeedRef.current = null
    fieldRevisionsRef.current = createInitialPullRequestFieldRevisions()
    baseEditedByUserRef.current = false
    syncedDefaultBaseRef.current = resolvedDefaultBaseRef || null
    setBase(resolvedDefaultBaseRef)
    setTitle(resolveCreateReviewDraftTitle({ branch, eligibilityTitle: eligibility.title }))
    setBody(eligibility.body ?? '')
    setDraft(resolvedPrDefaults.draft)
    invalidateBaseSearch()
  }, [
    branch,
    currentEligibilityKey,
    eligibility,
    hasExternalGeneration,
    invalidateBaseSearch,
    open,
    resolvedDefaultBaseRef,
    resolvedPrDefaults.draft
  ])

  const externalGenerationSeedRestoreKey = generation?.seedRestoreKey
  const externalGenerationSeed = generation?.seed
  const externalGenerationSeedFieldRevisions = generation?.seedFieldRevisions
  const onExternalGenerationSeedRestored = generation?.onSeedRestored

  useEffect(() => {
    if (
      !open ||
      !externalGenerationSeedRestoreKey ||
      !externalGenerationSeed ||
      !externalGenerationSeedFieldRevisions ||
      !initializedFromEligibilityRef.current ||
      restoredExternalGenerationSeedRef.current === externalGenerationSeedRestoreKey
    ) {
      return
    }
    // Why: external generation survives unmounts, so restore its revision guards with its seed.
    restoredExternalGenerationSeedRef.current = externalGenerationSeedRestoreKey
    fieldRevisionsRef.current = { ...externalGenerationSeedFieldRevisions }
    baseEditedByUserRef.current = true
    setBase(stripBaseRef(externalGenerationSeed.base))
    setTitle(externalGenerationSeed.title)
    setBody(externalGenerationSeed.body)
    setDraft(externalGenerationSeed.draft)
    invalidateBaseSearch()
    onExternalGenerationSeedRestored?.(externalGenerationSeedRestoreKey)
  }, [
    externalGenerationSeed,
    externalGenerationSeedFieldRevisions,
    externalGenerationSeedRestoreKey,
    invalidateBaseSearch,
    onExternalGenerationSeedRestored,
    open
  ])

  // Why: syncing the default base ref on identity change has no IPC call or
  // external notification (unlike the two effects above), so it uses React's
  // documented render-time "adjust state when a prop changes" comparison
  // instead of an effect — it settles in one commit instead of a follow-up one.
  if (
    open &&
    eligibility &&
    initializedFromEligibilityRef.current &&
    resolvedDefaultBaseRef &&
    syncedDefaultBaseRef.current !== resolvedDefaultBaseRef
  ) {
    syncedDefaultBaseRef.current = resolvedDefaultBaseRef
    if (!baseEditedByUserRef.current) {
      markFieldDirty('base')
      setBase(resolvedDefaultBaseRef)
      invalidateBaseSearch()
    }
  }

  // Why: comparing epochs during render — rather than clearing query/results/
  // error inside the effects above — guarantees the three clear in the same
  // commit as whichever base reset triggered them. A render-time state update
  // never paints an intermediate frame (React restarts the render before
  // committing), so there is no frame where the results list still shows a
  // previous target's matches after the query has already cleared.
  if (clearedBaseSearchEpochRef.current !== baseSearchEpochRef.current) {
    clearedBaseSearchEpochRef.current = baseSearchEpochRef.current
    if (baseQuery) {
      setBaseQuery('')
    }
    if (baseResults.length > 0) {
      setBaseResults([])
    }
    if (baseSearchError) {
      setBaseSearchError(null)
    }
  }

  return {
    applyGeneratedFields,
    autoGeneratedForKeyRef,
    base,
    baseQuery,
    baseResults,
    baseSearchError,
    body,
    currentEligibilityKey,
    draft,
    fieldRevisionsRef,
    generateError,
    generateInFlightRef,
    generating,
    generationRequestIdRef,
    generationSeedRef,
    initializedEligibilityKey,
    initializedFromEligibilityRef,
    setBase,
    setBaseQuery,
    setBaseResults,
    setBaseSearchError,
    setBody: setUserBody,
    setDraft: setUserDraft,
    setGenerateError,
    setGenerating,
    setTitle: setUserTitle,
    setUserBase,
    title
  }
}

export type CreateReviewDialogFieldState = ReturnType<typeof useCreateReviewDialogFieldState>
