import type { SourceControlAiPrCreationDefaults } from '@yiru/runtime-protocol/workbench/source-control/ai-types'
import { useEffect, useRef, useState } from 'react'
import { useEventCallback } from '~renderer/react/use-event-callback'
import { cancelRuntimeGeneratePullRequestFields } from '~renderer/runtime/git-client'
import type {
  PullRequestFieldName,
  PullRequestFieldRevisions
} from '~renderer/workspace-panel/pull-request-generation-state'

import { stripBaseRef } from './create-review-base-ref'
import {
  createInitialPullRequestFieldRevisions,
  type GenerationSeed,
  type PullRequestDraftFields,
  type UseCreatePullRequestDialogFieldsOptions
} from './create-review-dialog-field-types'
import { resolveCreateReviewDraftTitle } from './create-review-draft-title'

type TaggedGenerateError = {
  key: string
  message: string
}

export function useCreateReviewDialogFieldState({
  options,
  resolvedDefaultBaseRef,
  resolvedPrDefaults
}: {
  options: UseCreatePullRequestDialogFieldsOptions
  resolvedDefaultBaseRef: string
  resolvedPrDefaults: Required<SourceControlAiPrCreationDefaults>
}) {
  const { branch, eligibility, generation, open, repoId, worktreeId, worktreePath } = options
  const initializedFromEligibilityRef = useRef<string | null>(null)
  const autoGeneratedForKeyRef = useRef<string | null>(null)
  const generateInFlightRef = useRef(false)
  const generationRequestIdRef = useRef(0)
  const generationSeedRef = useRef<GenerationSeed | null>(null)
  const restoredExternalGenerationSeedRef = useRef<string | null>(null)
  const fieldRevisionsRef = useRef<PullRequestFieldRevisions>(
    createInitialPullRequestFieldRevisions()
  )
  // Why: a base-ref typeahead session belongs to whichever base was last
  // committed programmatically. Bumping this epoch instead of clearing
  // query/results/error inline inside each reset effect lets one render-time
  // comparison below clear all three atomically, in the same commit as the
  // base reset — there is no follow-up frame where the query has cleared but
  // the results list still shows a previous target's matches.
  const [baseSearchEpoch, setBaseSearchEpoch] = useState(0)
  const [clearedBaseSearchEpoch, setClearedBaseSearchEpoch] = useState(0)
  const [initializedEligibilityKey, setInitializedEligibilityKey] = useState<string | null>(null)
  const [syncedDefaultBase, setSyncedDefaultBase] = useState<string | null>(null)
  const [isBaseEditedByUser, setIsBaseEditedByUser] = useState(false)
  const [restoredExternalGenerationSeedKey, setRestoredExternalGenerationSeedKey] = useState<
    string | null
  >(null)
  const [baseDefaultRevisionBump, setBaseDefaultRevisionBump] = useState(0)
  const [base, setBase] = useState('')
  const [title, setTitle] = useState('')
  const [body, setBody] = useState('')
  const [draft, setDraft] = useState(false)
  const [baseQuery, setBaseQuery] = useState('')
  const [baseResults, setBaseResults] = useState<string[]>([])
  const [baseSearchError, setBaseSearchError] = useState<string | null>(null)
  const [inFlightGenerationKey, setInFlightGenerationKey] = useState<string | null>(null)
  const [taggedGenerateError, setTaggedGenerateError] = useState<TaggedGenerateError | null>(null)
  const hasExternalGeneration = Boolean(generation)
  const currentEligibilityKey =
    open && eligibility ? `${repoId}:${worktreeId ?? worktreePath}:${branch}` : null
  // Why: generating/generateError are tagged by the eligibility key that
  // started them rather than cleared explicitly on close/reinit — an old tag
  // stops matching the new key by itself, so no synchronous setter call is
  // needed inside the reset effects below to hide a stale in-flight flag or
  // error message.
  const generating =
    inFlightGenerationKey !== null && inFlightGenerationKey === currentEligibilityKey
  const generateError =
    taggedGenerateError && taggedGenerateError.key === currentEligibilityKey
      ? taggedGenerateError.message
      : null

  const markFieldDirty = (field: PullRequestFieldName): void => {
    fieldRevisionsRef.current = {
      ...fieldRevisionsRef.current,
      [field]: fieldRevisionsRef.current[field] + 1
    }
  }
  const invalidateBaseSearch = useEventCallback((): void => {
    setBaseSearchEpoch((epoch) => epoch + 1)
  })
  const setUserBase = (value: string) => {
    setIsBaseEditedByUser(true)
    markFieldDirty('base')
    setBase(value)
  }
  const setUserTitle = (value: string) => {
    markFieldDirty('title')
    setTitle(value)
  }
  const setUserBody = (value: string) => {
    markFieldDirty('body')
    setBody(value)
  }
  const setUserDraft = (value: boolean) => {
    markFieldDirty('draft')
    setDraft(value)
  }
  const setGenerating = (value: boolean) => {
    setInFlightGenerationKey(value ? currentEligibilityKey : null)
  }
  const setGenerateError = (message: string | null) => {
    setTaggedGenerateError(
      message === null || currentEligibilityKey === null
        ? null
        : { key: currentEligibilityKey, message }
    )
  }
  const applyGeneratedFields = (
    fields: PullRequestDraftFields,
    seedRevisions: PullRequestFieldRevisions
  ) => {
    const currentRevisions = fieldRevisionsRef.current
    const nextFields = { base, title, body, draft }
    // Why: asynchronous generation may only replace fields untouched since its request began.
    if (currentRevisions.base === seedRevisions.base) {
      nextFields.base = stripBaseRef(fields.base)
      setBase(nextFields.base)
      invalidateBaseSearch()
    }
    if (currentRevisions.title === seedRevisions.title) {
      nextFields.title = fields.title
      setTitle(fields.title)
    }
    if (currentRevisions.body === seedRevisions.body) {
      nextFields.body = fields.body
      setBody(fields.body)
    }
    if (currentRevisions.draft === seedRevisions.draft) {
      nextFields.draft = fields.draft
      setDraft(fields.draft)
    }
    return nextFields
  }

  const externalGenerationSeedRestoreKey = generation?.seedRestoreKey
  const externalGenerationSeed = generation?.seed
  const externalGenerationSeedFieldRevisions = generation?.seedFieldRevisions
  const onExternalGenerationSeedRestored = generation?.onSeedRestored

  if (initializedEligibilityKey !== currentEligibilityKey) {
    setInitializedEligibilityKey(currentEligibilityKey)
    setSyncedDefaultBase(currentEligibilityKey ? resolvedDefaultBaseRef || null : null)
    setIsBaseEditedByUser(false)
    setRestoredExternalGenerationSeedKey(null)
    setBase(currentEligibilityKey ? resolvedDefaultBaseRef : '')
    setTitle(
      currentEligibilityKey && eligibility
        ? resolveCreateReviewDraftTitle({ branch, eligibilityTitle: eligibility.title })
        : ''
    )
    setBody(currentEligibilityKey ? (eligibility?.body ?? '') : '')
    setDraft(currentEligibilityKey ? resolvedPrDefaults.draft : false)
    setBaseQuery('')
    setBaseResults([])
    setBaseSearchError(null)
  }

  useEffect(() => {
    if (!hasExternalGeneration) {
      generationRequestIdRef.current += 1
      const requestContext = generationSeedRef.current?.context
      if (generateInFlightRef.current && requestContext?.worktreePath) {
        void cancelRuntimeGeneratePullRequestFields(requestContext)
      }
      generateInFlightRef.current = false
      generationSeedRef.current = null
    }
    initializedFromEligibilityRef.current = initializedEligibilityKey
    autoGeneratedForKeyRef.current = null
    restoredExternalGenerationSeedRef.current = null
    fieldRevisionsRef.current = createInitialPullRequestFieldRevisions()
  }, [
    autoGeneratedForKeyRef,
    generateInFlightRef,
    generationRequestIdRef,
    generationSeedRef,
    hasExternalGeneration,
    initializedEligibilityKey
  ])

  if (
    open &&
    externalGenerationSeedRestoreKey &&
    externalGenerationSeed &&
    externalGenerationSeedFieldRevisions &&
    initializedEligibilityKey &&
    restoredExternalGenerationSeedKey !== externalGenerationSeedRestoreKey
  ) {
    setRestoredExternalGenerationSeedKey(externalGenerationSeedRestoreKey)
    setIsBaseEditedByUser(true)
    setBase(stripBaseRef(externalGenerationSeed.base))
    setTitle(externalGenerationSeed.title)
    setBody(externalGenerationSeed.body)
    setDraft(externalGenerationSeed.draft)
    setBaseQuery('')
    setBaseResults([])
    setBaseSearchError(null)
  }

  useEffect(() => {
    if (
      !restoredExternalGenerationSeedKey ||
      restoredExternalGenerationSeedKey !== externalGenerationSeedRestoreKey ||
      !externalGenerationSeedFieldRevisions
    ) {
      return
    }
    restoredExternalGenerationSeedRef.current = restoredExternalGenerationSeedKey
    fieldRevisionsRef.current = { ...externalGenerationSeedFieldRevisions }
    onExternalGenerationSeedRestored?.(restoredExternalGenerationSeedKey)
  }, [
    externalGenerationSeed,
    externalGenerationSeedFieldRevisions,
    externalGenerationSeedRestoreKey,
    onExternalGenerationSeedRestored,
    restoredExternalGenerationSeedKey
  ])

  // Why: syncing the default base ref on identity change has no IPC call or
  // external notification (unlike the two effects above), so it uses React's
  // documented render-time "adjust state when a prop changes" comparison
  // instead of an effect — it settles in one commit instead of a follow-up one.
  if (
    open &&
    eligibility &&
    initializedEligibilityKey &&
    resolvedDefaultBaseRef &&
    syncedDefaultBase !== resolvedDefaultBaseRef
  ) {
    setSyncedDefaultBase(resolvedDefaultBaseRef)
    if (!isBaseEditedByUser) {
      setBaseDefaultRevisionBump((revision) => revision + 1)
      setBase(resolvedDefaultBaseRef)
      invalidateBaseSearch()
    }
  }

  useEffect(() => {
    if (baseDefaultRevisionBump > 0) {
      markFieldDirty('base')
    }
  }, [baseDefaultRevisionBump])

  // Why: comparing epochs during render — rather than clearing query/results/
  // error inside the effects above — guarantees the three clear in the same
  // commit as whichever base reset triggered them. A render-time state update
  // never paints an intermediate frame (React restarts the render before
  // committing), so there is no frame where the results list still shows a
  // previous target's matches after the query has already cleared.
  if (clearedBaseSearchEpoch !== baseSearchEpoch) {
    setClearedBaseSearchEpoch(baseSearchEpoch)
    if (baseQuery) {
      setBaseQuery('')
    }
    if (baseResults.length > 0) {
      setBaseResults([])
    }
    if (baseSearchError) {
      setBaseSearchError(null)
    }
  }

  return {
    applyGeneratedFields,
    autoGeneratedForKeyRef,
    base,
    baseQuery,
    baseResults,
    baseSearchError,
    body,
    currentEligibilityKey,
    draft,
    fieldRevisionsRef,
    generateError,
    generateInFlightRef,
    generating,
    generationRequestIdRef,
    generationSeedRef,
    initializedEligibilityKey,
    initializedFromEligibilityRef,
    setBase,
    setBaseQuery,
    setBaseResults,
    setBaseSearchError,
    setBody: setUserBody,
    setDraft: setUserDraft,
    setGenerateError,
    setGenerating,
    setTitle: setUserTitle,
    setUserBase,
    title
  }
}

export type CreateReviewDialogFieldState = ReturnType<typeof useCreateReviewDialogFieldState>
