import { cn } from '@/style/class-names'

export const mobileDiffReviewLayoutStyles = {
  safeArea: cn('flex-1 bg-background'),
  header: cn('px-4 pb-2 border-b-hairline border-b-border'),
  topBar: cn('min-h-[50px] flex-row items-center gap-2'),
  iconButton: cn('w-11 h-11 rounded-none items-center justify-center'),
  iconButtonPressed: cn('bg-secondary'),
  titleBlock: cn('flex-1 min-w-0'),
  title: cn('text-foreground text-[18px] font-bold'),
  subtitle: cn('text-muted-foreground/60 text-[12px] mt-[2px]'),
  progressRow: cn('flex-row justify-between gap-3'),
  progressText: cn('text-muted-foreground text-[12px] font-semibold'),
  filterRow: cn('gap-2 pt-3 pb-1'),
  filterChip: cn(
    'min-h-[34px] rounded-none px-3 items-center justify-center bg-card border-hairline border-border'
  ),
  filterChipActive: cn('bg-foreground border-foreground'),
  filterChipPressed: cn('opacity-[0.78]'),
  filterText: cn('text-muted-foreground text-[12px] font-bold'),
  filterTextActive: cn('text-background'),
  fileHeader: cn('px-4 pt-3 pb-2 bg-background border-b-hairline border-b-border'),
  fileTitleRow: cn('flex-row items-center gap-2'),
  statusBadge: cn('w-7 h-7 rounded-none border-hairline items-center justify-center'),
  statusBadgeText: cn('text-[12px] font-extrabold'),
  fileTitleBlock: cn('flex-1 min-w-0'),
  filePath: cn('text-foreground text-[14px] font-bold'),
  fileMeta: cn('text-muted-foreground/60 text-[12px] mt-[2px]'),
  fileMetaRow: cn('flex-row items-center gap-2 mt-2 flex-wrap'),
  reviewedPill: cn('text-green-500 text-[12px] font-bold'),
  stalePill: cn('text-amber-500 text-[12px] font-bold'),
  staleText: cn('text-amber-500 text-[12px] font-bold'),
  fileNotes: cn('gap-1 mt-2'),
  fileNote: cn('min-h-11 p-2 rounded-none bg-card border-hairline border-border'),
  fileNotePressed: cn('bg-secondary'),
  fileNoteText: cn('text-muted-foreground text-[12px] leading-[17px]'),
  hunkRow: cn('flex-row gap-2 mt-2'),
  hunkButton: cn('min-h-9 flex-row items-center justify-center gap-1 px-3 rounded-none bg-card'),
  hunkButtonPressed: cn('bg-secondary'),
  hunkButtonText: cn('text-muted-foreground text-[12px] font-bold'),
  actionError: cn('mx-4 mt-2 px-3 py-2 rounded-none bg-secondary border-hairline border-amber-500'),
  actionErrorText: cn('text-foreground text-[12px]'),
  diffList: cn('pb-[140px] bg-[var(--editor-surface)]'),
  truncatedText: cn('text-muted-foreground/60 text-[12px] p-3 text-center'),
  state: cn('flex-1 items-center justify-center p-6 gap-3'),
  stateTitle: cn('text-foreground text-[18px] font-bold text-center'),
  stateText: cn('text-muted-foreground text-[14px] text-center leading-[20px]'),
  retryButton: cn('min-h-11 flex-row items-center gap-1 px-3 rounded-none bg-secondary'),
  retryText: cn('text-foreground text-[14px] font-bold')
} as const
