import * as Phosphor from 'phosphor-react-native'
import { createElement, type ComponentType } from 'react'
import { withUniwind } from 'uniwind'

// Why: Phosphor does not expose native className props, so this module keeps
// icon colors on the same Uniwind token path as the surrounding interface.
function withRegularWeight(Icon: Phosphor.Icon) {
  // Why: directional and compact action chrome matches desktop's quieter
  // regular treatment while other mobile icons continue to inherit duotone.
  return withUniwind((props: Phosphor.IconProps) =>
    createElement(Icon, { ...props, weight: props.weight ?? 'regular' })
  )
}

export const ArrowClockwise = withRegularWeight(Phosphor.ArrowClockwise)
export const ArrowCounterClockwise = withRegularWeight(Phosphor.ArrowCounterClockwise)
export const ArrowDown = withRegularWeight(Phosphor.ArrowDown)
export const ArrowElbowDownRight = withRegularWeight(Phosphor.ArrowElbowDownRight)
export const ArrowRight = withRegularWeight(Phosphor.ArrowRight)
export const ArrowSquareOut = withRegularWeight(Phosphor.ArrowSquareOut)
export const ArrowSquareRight = withRegularWeight(Phosphor.ArrowSquareRight)
export const ArrowUp = withRegularWeight(Phosphor.ArrowUp)
export const ArrowsClockwise = withRegularWeight(Phosphor.ArrowsClockwise)
export const ArrowsDownUp = withRegularWeight(Phosphor.ArrowsDownUp)
export const ArrowsInLineVertical = withRegularWeight(Phosphor.ArrowsInLineVertical)
export const ArrowsOutLineVertical = withRegularWeight(Phosphor.ArrowsOutLineVertical)
export const Bell = withUniwind(Phosphor.Bell)
export const BellRinging = withUniwind(Phosphor.BellRinging)
export const BracketsCurly = withUniwind(Phosphor.BracketsCurly)
export const Briefcase = withUniwind(Phosphor.Briefcase)
export const Buildings = withUniwind(Phosphor.Buildings)
export const CaretDoubleRight = withRegularWeight(Phosphor.CaretDoubleRight)
export const CaretDown = withRegularWeight(Phosphor.CaretDown)
export const CaretLeft = withRegularWeight(Phosphor.CaretLeft)
export const CaretRight = withRegularWeight(Phosphor.CaretRight)
export const CaretUp = withRegularWeight(Phosphor.CaretUp)
export const Chat = withUniwind(Phosphor.Chat)
export const Check = withUniwind(Phosphor.Check)
export const CheckCircle = withUniwind(Phosphor.CheckCircle)
export const Clipboard = withUniwind(Phosphor.Clipboard)
export const Clock = withUniwind(Phosphor.Clock)
export const ClockCounterClockwise = withUniwind(Phosphor.ClockCounterClockwise)
export const CloudArrowUp = withRegularWeight(Phosphor.CloudArrowUp)
export const Code = withUniwind(Phosphor.Code)
export const CodeSimple = withUniwind(Phosphor.CodeSimple)
export const Copy = withUniwind(Phosphor.Copy)
export const Cpu = withUniwind(Phosphor.Cpu)
export const Cube = withUniwind(Phosphor.Cube)
export const Database = withUniwind(Phosphor.Database)
export const DeviceMobile = withUniwind(Phosphor.DeviceMobile)
export const DotsSixVertical = withUniwind(Phosphor.DotsSixVertical)
export const DotsThree = withUniwind(Phosphor.DotsThree)
export const Download = withUniwind(Phosphor.Download)
export const Eraser = withUniwind(Phosphor.Eraser)
export const Eye = withUniwind(Phosphor.Eye)
export const File = withUniwind(Phosphor.File)
export const FileCode = withUniwind(Phosphor.FileCode)
export const FileText = withUniwind(Phosphor.FileText)
export const FileX = withUniwind(Phosphor.FileX)
export const FloppyDisk = withUniwind(Phosphor.FloppyDisk)
export const Folder = withUniwind(Phosphor.Folder)
export const Funnel = withUniwind(Phosphor.Funnel)
export const Gauge = withUniwind(Phosphor.Gauge)
export const Gear = withUniwind(Phosphor.Gear)
export const GitBranch = withUniwind(Phosphor.GitBranch)
export const GithubLogo = withUniwind(Phosphor.GithubLogo)
export const GitlabLogo = withUniwind(Phosphor.GitlabLogo)
export const GitMerge = withUniwind(Phosphor.GitMerge)
export const GitPullRequest = withUniwind(Phosphor.GitPullRequest)
export const Globe = withUniwind(Phosphor.Globe)
export const HardDrives = withUniwind(Phosphor.HardDrives)
export const Image = withUniwind(Phosphor.Image)
export const ImageSquare = withUniwind(Phosphor.ImageSquare)
export const Info = withUniwind(Phosphor.Info)
export const Key = withUniwind(Phosphor.Key)
export const Keyboard = withUniwind(Phosphor.Keyboard)
export const Lifebuoy = withUniwind(Phosphor.Lifebuoy)
export const Link = withUniwind(Phosphor.Link)
export const LinkBreak = withUniwind(Phosphor.LinkBreak)
export const LinkSimple = withUniwind(Phosphor.LinkSimple)
export const List = withUniwind(Phosphor.List)
export const ListChecks = withUniwind(Phosphor.ListChecks)
export const ListNumbers = withUniwind(Phosphor.ListNumbers)
export const MagnifyingGlass = withUniwind(Phosphor.MagnifyingGlass)
export const Microphone = withUniwind(Phosphor.Microphone)
export const Minus = withUniwind(Phosphor.Minus)
export const Monitor = withUniwind(Phosphor.Monitor)
export const Moon = withUniwind(Phosphor.Moon)
export const Package = withUniwind(Phosphor.Package)
export const Palette = withUniwind(Phosphor.Palette)
export const PaperPlaneTilt = withUniwind(Phosphor.PaperPlaneTilt)
export const Paragraph = withUniwind(Phosphor.Paragraph)
export const Pencil = withUniwind(Phosphor.Pencil)
export const PencilSimple = withUniwind(Phosphor.PencilSimple)
export const Play = withUniwind(Phosphor.Play)
export const Plus = withUniwind(Phosphor.Plus)
export const Power = withUniwind(Phosphor.Power)
export const Pulse = withUniwind(Phosphor.Pulse)
export const PushPin = withUniwind(Phosphor.PushPin)
export const QrCode = withUniwind(Phosphor.QrCode)
export const Question = withUniwind(Phosphor.Question)
export const Quotes = withUniwind(Phosphor.Quotes)
export const RadioButton = withUniwind(Phosphor.RadioButton)
export const Robot = withUniwind(Phosphor.Robot)
export const Rocket = withUniwind(Phosphor.Rocket)
export const Scroll = withUniwind(Phosphor.Scroll)
export const SealQuestion = withUniwind(Phosphor.SealQuestion)
export const Shapes = withUniwind(Phosphor.Shapes)
export const Shield = withUniwind(Phosphor.Shield)
export const SidebarSimple = withRegularWeight(Phosphor.SidebarSimple)
export const SlidersHorizontal = withUniwind(Phosphor.SlidersHorizontal)
export const Sparkle = withUniwind(Phosphor.Sparkle)
export const Square = withUniwind(Phosphor.Square)
export const Stack = withUniwind(Phosphor.Stack)
export const Terminal = withUniwind(Phosphor.Terminal)
export const TerminalWindow = withUniwind(Phosphor.TerminalWindow)
export const TextAa = withUniwind(Phosphor.TextAa)
export const TextB = withUniwind(Phosphor.TextB)
export const TextHOne = withUniwind(Phosphor.TextHOne)
export const TextHThree = withUniwind(Phosphor.TextHThree)
export const TextHTwo = withUniwind(Phosphor.TextHTwo)
export const TextItalic = withUniwind(Phosphor.TextItalic)
export const TextStrikethrough = withUniwind(Phosphor.TextStrikethrough)
export const TextT = withUniwind(Phosphor.TextT)
export const Trash = withUniwind(Phosphor.Trash)
export const User = withUniwind(Phosphor.User)
export const UserCircle = withUniwind(Phosphor.UserCircle)
export const UserPlus = withUniwind(Phosphor.UserPlus)
export const Warning = withUniwind(Phosphor.Warning)
export const WifiSlash = withUniwind(Phosphor.WifiSlash)
export const Wrench = withUniwind(Phosphor.Wrench)
export const X = withRegularWeight(Phosphor.X)
export const XCircle = withUniwind(Phosphor.XCircle)

export { IconContext } from 'phosphor-react-native'
export type Icon = ComponentType<Phosphor.IconProps & { colorClassName?: string }>
