import * as Phosphor from 'phosphor-react-native'
import { createElement, type ComponentType } from 'react'
import { withUniwind } from 'uniwind'

// Why: Phosphor does not expose native className props, so this module keeps
// icon colors on Uniwind's token path and gives every mobile icon one default weight.
function withMobileIcon(Icon: Phosphor.Icon) {
  return withUniwind((props: Phosphor.IconProps) =>
    createElement(Icon, { ...props, weight: props.weight ?? 'regular' })
  )
}

export const ArrowClockwise = withMobileIcon(Phosphor.ArrowClockwise)
export const ArrowCounterClockwise = withMobileIcon(Phosphor.ArrowCounterClockwise)
export const ArrowDown = withMobileIcon(Phosphor.ArrowDown)
export const ArrowElbowDownRight = withMobileIcon(Phosphor.ArrowElbowDownRight)
export const ArrowRight = withMobileIcon(Phosphor.ArrowRight)
export const ArrowSquareOut = withMobileIcon(Phosphor.ArrowSquareOut)
export const ArrowSquareRight = withMobileIcon(Phosphor.ArrowSquareRight)
export const ArrowUp = withMobileIcon(Phosphor.ArrowUp)
export const ArrowsClockwise = withMobileIcon(Phosphor.ArrowsClockwise)
export const ArrowsDownUp = withMobileIcon(Phosphor.ArrowsDownUp)
export const ArrowsOutCardinal = withMobileIcon(Phosphor.ArrowsOutCardinal)
export const ArrowsInLineVertical = withMobileIcon(Phosphor.ArrowsInLineVertical)
export const ArrowsOutLineVertical = withMobileIcon(Phosphor.ArrowsOutLineVertical)
export const Bell = withMobileIcon(Phosphor.Bell)
export const BellRinging = withMobileIcon(Phosphor.BellRinging)
export const BellSimple = withMobileIcon(Phosphor.BellSimple)
export const BracketsCurly = withMobileIcon(Phosphor.BracketsCurly)
export const Briefcase = withMobileIcon(Phosphor.Briefcase)
export const Buildings = withMobileIcon(Phosphor.Buildings)
export const Camera = withMobileIcon(Phosphor.Camera)
export const CaretDoubleRight = withMobileIcon(Phosphor.CaretDoubleRight)
export const CaretDown = withMobileIcon(Phosphor.CaretDown)
export const CaretLeft = withMobileIcon(Phosphor.CaretLeft)
export const CaretRight = withMobileIcon(Phosphor.CaretRight)
export const CaretUp = withMobileIcon(Phosphor.CaretUp)
export const ChartBar = withMobileIcon(Phosphor.ChartBar)
export const Chat = withMobileIcon(Phosphor.Chat)
export const Check = withMobileIcon(Phosphor.Check)
export const CheckCircle = withMobileIcon(Phosphor.CheckCircle)
export const Clipboard = withMobileIcon(Phosphor.Clipboard)
export const Clock = withMobileIcon(Phosphor.Clock)
export const ClockCounterClockwise = withMobileIcon(Phosphor.ClockCounterClockwise)
export const CloudArrowUp = withMobileIcon(Phosphor.CloudArrowUp)
export const Code = withMobileIcon(Phosphor.Code)
export const CodeSimple = withMobileIcon(Phosphor.CodeSimple)
export const Copy = withMobileIcon(Phosphor.Copy)
export const Cpu = withMobileIcon(Phosphor.Cpu)
export const Cube = withMobileIcon(Phosphor.Cube)
export const Database = withMobileIcon(Phosphor.Database)
export const DeviceMobile = withMobileIcon(Phosphor.DeviceMobile)
export const DotsSixVertical = withMobileIcon(Phosphor.DotsSixVertical)
export const DotsThree = withMobileIcon(Phosphor.DotsThree)
export const Download = withMobileIcon(Phosphor.Download)
export const Eraser = withMobileIcon(Phosphor.Eraser)
export const Eye = withMobileIcon(Phosphor.Eye)
export const File = withMobileIcon(Phosphor.File)
export const FileCode = withMobileIcon(Phosphor.FileCode)
export const FileText = withMobileIcon(Phosphor.FileText)
export const FileX = withMobileIcon(Phosphor.FileX)
export const Files = withMobileIcon(Phosphor.Files)
export const FloppyDisk = withMobileIcon(Phosphor.FloppyDisk)
export const Folder = withMobileIcon(Phosphor.Folder)
export const Funnel = withMobileIcon(Phosphor.Funnel)
export const Gauge = withMobileIcon(Phosphor.Gauge)
export const Gear = withMobileIcon(Phosphor.Gear)
export const GithubLogo = withMobileIcon(Phosphor.GithubLogo)
export const GitlabLogo = withMobileIcon(Phosphor.GitlabLogo)
export const GitMerge = withMobileIcon(Phosphor.GitMerge)
export const GitPullRequest = withMobileIcon(Phosphor.GitPullRequest)
export const Globe = withMobileIcon(Phosphor.Globe)
export const HardDrives = withMobileIcon(Phosphor.HardDrives)
export const Image = withMobileIcon(Phosphor.Image)
export const ImageSquare = withMobileIcon(Phosphor.ImageSquare)
export const Info = withMobileIcon(Phosphor.Info)
export const Key = withMobileIcon(Phosphor.Key)
export const Keyboard = withMobileIcon(Phosphor.Keyboard)
export const Lifebuoy = withMobileIcon(Phosphor.Lifebuoy)
export const Link = withMobileIcon(Phosphor.Link)
export const LinkBreak = withMobileIcon(Phosphor.LinkBreak)
export const LinkSimple = withMobileIcon(Phosphor.LinkSimple)
export const List = withMobileIcon(Phosphor.List)
export const ListChecks = withMobileIcon(Phosphor.ListChecks)
export const ListNumbers = withMobileIcon(Phosphor.ListNumbers)
export const MagnifyingGlass = withMobileIcon(Phosphor.MagnifyingGlass)
export const Minus = withMobileIcon(Phosphor.Minus)
export const Monitor = withMobileIcon(Phosphor.Monitor)
export const Moon = withMobileIcon(Phosphor.Moon)
export const Package = withMobileIcon(Phosphor.Package)
export const Palette = withMobileIcon(Phosphor.Palette)
export const PaperPlaneTilt = withMobileIcon(Phosphor.PaperPlaneTilt)
export const Paragraph = withMobileIcon(Phosphor.Paragraph)
export const Pencil = withMobileIcon(Phosphor.Pencil)
export const PencilSimple = withMobileIcon(Phosphor.PencilSimple)
export const Play = withMobileIcon(Phosphor.Play)
export const Plus = withMobileIcon(Phosphor.Plus)
export const Power = withMobileIcon(Phosphor.Power)
export const Pulse = withMobileIcon(Phosphor.Pulse)
export const PushPin = withMobileIcon(Phosphor.PushPin)
export const QrCode = withMobileIcon(Phosphor.QrCode)
export const Question = withMobileIcon(Phosphor.Question)
export const Quotes = withMobileIcon(Phosphor.Quotes)
export const RadioButton = withMobileIcon(Phosphor.RadioButton)
export const Robot = withMobileIcon(Phosphor.Robot)
export const Rocket = withMobileIcon(Phosphor.Rocket)
export const Scroll = withMobileIcon(Phosphor.Scroll)
export const SealQuestion = withMobileIcon(Phosphor.SealQuestion)
export const Shapes = withMobileIcon(Phosphor.Shapes)
export const Shield = withMobileIcon(Phosphor.Shield)
export const SidebarSimple = withMobileIcon(Phosphor.SidebarSimple)
export const SlidersHorizontal = withMobileIcon(Phosphor.SlidersHorizontal)
export const Sparkle = withMobileIcon(Phosphor.Sparkle)
export const Square = withMobileIcon(Phosphor.Square)
export const Stack = withMobileIcon(Phosphor.Stack)
export const Terminal = withMobileIcon(Phosphor.Terminal)
export const TerminalWindow = withMobileIcon(Phosphor.TerminalWindow)
export const TextAa = withMobileIcon(Phosphor.TextAa)
export const TextB = withMobileIcon(Phosphor.TextB)
export const TextHOne = withMobileIcon(Phosphor.TextHOne)
export const TextHThree = withMobileIcon(Phosphor.TextHThree)
export const TextHTwo = withMobileIcon(Phosphor.TextHTwo)
export const TextItalic = withMobileIcon(Phosphor.TextItalic)
export const TextStrikethrough = withMobileIcon(Phosphor.TextStrikethrough)
export const TextT = withMobileIcon(Phosphor.TextT)
export const Trash = withMobileIcon(Phosphor.Trash)
export const User = withMobileIcon(Phosphor.User)
export const UserCircle = withMobileIcon(Phosphor.UserCircle)
export const UserPlus = withMobileIcon(Phosphor.UserPlus)
export const Warning = withMobileIcon(Phosphor.Warning)
export const WifiSlash = withMobileIcon(Phosphor.WifiSlash)
export const Wrench = withMobileIcon(Phosphor.Wrench)
export const X = withMobileIcon(Phosphor.X)
export const XCircle = withMobileIcon(Phosphor.XCircle)

export { IconContext } from 'phosphor-react-native'
export type Icon = ComponentType<Phosphor.IconProps & { colorClassName?: string }>
