// Why: Swift cannot consume the TypeScript mobile schemas or path constants at build time.
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { z } from 'zod'

const WIRE_MODULES = [
  'mobile-accounts-wire',
  'mobile-agent-history-wire',
  'mobile-agent-status-wire',
  'mobile-browser-wire',
  'mobile-client-events-wire',
  'mobile-clipboard-wire',
  'mobile-files-wire',
  'mobile-github-review-wire',
  'mobile-hosted-review-wire',
  'mobile-notifications-wire',
  'mobile-review-wire',
  'mobile-session-content-wire',
  'mobile-session-tabs-wire',
  'mobile-source-control-wire',
  'mobile-stats-wire',
  'mobile-terminal-quick-commands-wire',
  'mobile-terminal-wire',
  'mobile-workspace-creation-wire',
  'mobile-worktree-wire'
]
const TRANSPORT_MODULES = ['mobile/e2ee-contract', 'mobile/e2ee-framing', 'mobile/pairing-offer']
const OUTPUT_URL = new URL(
  '../YiruMobile/Platform/Wire/Generated/MobileWire.generated.swift',
  import.meta.url
)
const TEMPLATE_URL = new URL('./mobile-wire.swift.template', import.meta.url)
const FORMAT_CONFIGURATION_URL = new URL('../.swift-format', import.meta.url)

const contract = await loadContract()
const digest = createHash('sha256')
  .update(`${JSON.stringify(contract, null, 2)}\n`)
  .digest('hex')
const template = await readFile(TEMPLATE_URL, 'utf8')
const declarations = renderPathDeclarations(contract.paths)
const source = template.replace('{{MOBILE_ORPC_PATH_DECLARATIONS}}', declarations)
if (source.includes('{{')) {
  throw new Error('Mobile wire template contains an unresolved generator token')
}
const header =
  '// Generated by apps/mobile/scripts/generate-wire.mjs. Do not edit.\n' +
  `// Mobile wire schemas SHA-256: ${digest}\n\n`
const generated = formatSwift(`${header}${source}`)

await writeFile(OUTPUT_URL, generated)
process.stdout.write(`Wrote ${fileURLToPath(OUTPUT_URL)}\n`)

async function loadContract() {
  const schemas = {}
  const paths = {}
  const transport = {}
  for (const moduleName of WIRE_MODULES) {
    const exports = await import(`@yiru/runtime-protocol/${moduleName}`)
    const moduleSchemas = {}
    collectSchemasAndPaths(exports, moduleSchemas, paths)
    schemas[moduleName] = sortRecord(moduleSchemas)
  }
  for (const moduleName of TRANSPORT_MODULES) {
    const exports = await import(`@yiru/runtime-protocol/${moduleName}`)
    const moduleSchemas = {}
    const constants = {}
    collectSchemasAndConstants(exports, moduleSchemas, constants)
    transport[moduleName] = {
      schemas: sortRecord(moduleSchemas),
      constants: sortRecord(constants)
    }
  }
  return {
    schemas: sortRecord(schemas),
    paths: sortRecord(paths),
    transport: sortRecord(transport)
  }
}

function collectSchemasAndPaths(exports, schemas, paths) {
  for (const [name, value] of Object.entries(exports)) {
    if (name.endsWith('Schema') && isZodSchema(value)) {
      schemas[name] = z.toJSONSchema(value, { unrepresentable: 'any' })
    } else if (/^MOBILE_.*_ORPC_PATH$/.test(name) && typeof value === 'string') {
      paths[name] = value
    }
  }
}

function collectSchemasAndConstants(exports, schemas, constants) {
  for (const [name, value] of Object.entries(exports)) {
    if (name.endsWith('Schema') && isZodSchema(value)) {
      schemas[name] = z.toJSONSchema(value, { unrepresentable: 'any' })
    } else if (typeof value === 'string' || typeof value === 'number') {
      constants[name] = value
    }
  }
}

function isZodSchema(value) {
  return typeof value === 'object' && value !== null && '_zod' in value
}

function sortRecord(record) {
  return Object.fromEntries(
    Object.entries(record).sort(([left], [right]) => left.localeCompare(right))
  )
}

function renderPathDeclarations(paths) {
  const values = Object.entries(paths).map(
    ([name, value]) => `    static let ${swiftPathName(name)} = ${JSON.stringify(value)}`
  )
  return `nonisolated enum MobileORPCPath {\n${values.join('\n')}\n}`
}

function swiftPathName(name) {
  const words = name.toLowerCase().split('_')
  return (
    words[0] +
    words
      .slice(1)
      .map((word) => word[0].toUpperCase() + word.slice(1))
      .join('')
  )
}

function formatSwift(source) {
  return execFileSync(
    'xcrun',
    [
      'swift-format',
      'format',
      '--configuration',
      fileURLToPath(FORMAT_CONFIGURATION_URL),
      '--assume-filename',
      fileURLToPath(OUTPUT_URL),
      '-'
    ],
    { input: source, encoding: 'utf8' }
  )
}
