#!/usr/bin/env bash
# Why: release publishing spans npm, Chrome Web Store, Apple, and Cloudflare credentials that
# require one-time browser setup and must be stored in GitHub rather than a developer checkout.
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPOSITORY="xinyao27/yiru"
CHROME_ENVIRONMENT="chrome-web-store"

has_repo_secret() {
  gh secret list --repo "$REPOSITORY" --json name --jq '.[].name' 2>/dev/null |
    grep -Fxq "$1"
}

has_environment_secret() {
  gh secret list --repo "$REPOSITORY" --env "$CHROME_ENVIRONMENT" \
    --json name --jq '.[].name' 2>/dev/null | grep -Fxq "$1"
}

set_environment_secret() {
  local name="$1" value="$2"
  if printf '%s' "$value" |
    gh secret set "$name" --repo "$REPOSITORY" --env "$CHROME_ENVIRONMENT" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$CHROME_ENVIRONMENT/$name")
    printf '  %s✓ set%s GitHub environment secret %s\n' "$GREEN" "$RESET" "$name"
    return
  fi
  SKIPPED+=("GitHub environment secret $CHROME_ENVIRONMENT/$name")
  warn "could not set $CHROME_ENVIRONMENT/$name"
}

banner "Yiru release setup"

stage "GitHub release environment"
say "We'll verify GitHub CLI access and create the protected Chrome publishing environment."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is not authenticated. Run: gh auth login"
  exit 1
fi
resolved_repo=$(gh repo view --json nameWithOwner --jq '.nameWithOwner')
if [[ "$resolved_repo" != "$REPOSITORY" ]]; then
  warn "This directory resolves to $resolved_repo, expected $REPOSITORY."
  exit 1
fi
gh api --method PUT "repos/$REPOSITORY/environments/$CHROME_ENVIRONMENT" >/dev/null
say "GitHub environment $CHROME_ENVIRONMENT is ready."
note "Add required reviewers later in GitHub Settings → Environments if releases need approval."
pause "Continue to registry credentials?"

stage "npm first publication"
if has_repo_secret NPM_TOKEN; then
  say "NPM_TOKEN already exists; leaving it unchanged."
else
  say "The @yiru/cli package does not exist yet, so its first CI publication needs a token."
  open_url "https://www.npmjs.com/"
  step "Sign in and confirm your account can publish public packages under the @yiru scope."
  step "Open your avatar → Access Tokens → Generate New Token → Granular Access Token."
  step "Grant read/write package access for @yiru, enable publishing 2FA bypass, and generate it."
  step "Copy the token now; npm will not display the complete value again."
  ask_secret NPM_TOKEN "Paste the npm token:"
  if [[ -z "$NPM_TOKEN" ]]; then
    warn "NPM_TOKEN cannot be empty."
    exit 1
  fi
  set_secret NPM_TOKEN "$NPM_TOKEN"
fi
note "After the first release, replace this token with npm Trusted Publishing as documented."
pause "Continue to Chrome Web Store OAuth?"

stage "Chrome Web Store OAuth client"
if has_environment_secret CWS_CLIENT_ID && has_environment_secret CWS_CLIENT_SECRET; then
  say "Chrome OAuth client secrets already exist; leaving them unchanged."
else
  say "We'll enable Chrome Web Store API v2 and create the OAuth client used by GitHub Actions."
  open_url "https://console.cloud.google.com/apis/library/chromewebstore.googleapis.com"
  step "Select the Google Cloud project that owns the publishing integration, then enable the API."
  step "Open APIs & Services → OAuth consent screen and complete its required app details."
  step "Open Credentials → Create Credentials → OAuth client ID → Web application."
  step "Add https://developers.google.com/oauthplayground as an authorized redirect URI."
  step "Create the client, then copy its client ID and client secret."
  ask CWS_CLIENT_ID "Paste the OAuth client ID:"
  ask_secret CWS_CLIENT_SECRET "Paste the OAuth client secret:"
  set_environment_secret CWS_CLIENT_ID "$CWS_CLIENT_ID"
  set_environment_secret CWS_CLIENT_SECRET "$CWS_CLIENT_SECRET"
fi
pause "Continue to the Web Store refresh token?"

stage "Chrome publisher and refresh token"
if has_environment_secret CWS_PUBLISHER_ID && has_environment_secret CWS_REFRESH_TOKEN; then
  say "Chrome publisher and refresh token secrets already exist; leaving them unchanged."
else
  open_url "https://developers.google.com/oauthplayground"
  step "Open settings, enable Use your own OAuth credentials, and enter the client from Stage 3."
  step "Use scope https://www.googleapis.com/auth/chromewebstore and click Authorize APIs."
  step "Sign in as the Web Store item owner, then click Exchange authorization code for tokens."
  step "Copy the refresh token, not the short-lived access token."
  ask_secret CWS_REFRESH_TOKEN "Paste the refresh token:"
  open_url "https://chrome.google.com/webstore/devconsole"
  step "Switch to the publisher that owns Yiru, then open Publisher → Settings."
  step "Copy the Publisher ID shown on that page."
  ask CWS_PUBLISHER_ID "Paste the publisher ID:"
  set_environment_secret CWS_REFRESH_TOKEN "$CWS_REFRESH_TOKEN"
  set_environment_secret CWS_PUBLISHER_ID "$CWS_PUBLISHER_ID"
fi
pause "Continue to optional iPhone background notifications?"

stage "Optional APNs gateway"
if has_repo_secret CLOUDFLARE_ACCOUNT_ID && has_repo_secret CLOUDFLARE_API_TOKEN &&
  has_repo_secret APNS_KEY_ID && has_repo_secret APNS_KEY_P8 &&
  has_repo_secret APNS_TEAM_ID && has_repo_secret GATEWAY_SHARED_SECRET; then
  say "All APNs gateway credentials already exist; leaving them unchanged."
  set_var APNS_GATEWAY_ENABLED true
elif ! confirm "Configure optional iPhone background notifications now?"; then
  SKIPPED+=("optional APNs gateway credentials")
  set_var APNS_GATEWAY_ENABLED false
  say "Skipped. Chrome, the required daemon runtime, and foreground iOS remain available."
else
  open_url "https://dash.cloudflare.com/"
  if has_repo_secret CLOUDFLARE_ACCOUNT_ID; then
    say "CLOUDFLARE_ACCOUNT_ID already exists; leaving it unchanged."
  else
    step "Select the account that will host the APNs gateway Worker."
    step "Copy the Account ID shown in the account overview URL or account details."
    ask CLOUDFLARE_ACCOUNT_ID "Paste the Cloudflare account ID:"
    set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
  fi
  if has_repo_secret CLOUDFLARE_API_TOKEN; then
    say "CLOUDFLARE_API_TOKEN already exists; leaving it unchanged."
  else
    open_url "https://dash.cloudflare.com/profile/api-tokens"
    step "Create a token with Workers Scripts write access, scoped to the Yiru account."
    step "Copy the token after Cloudflare creates it."
    ask_secret CLOUDFLARE_API_TOKEN "Paste the Cloudflare API token:"
    set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
  fi

  open_url "https://developer.apple.com/account/resources/authkeys/list"
  if has_repo_secret APNS_KEY_ID && has_repo_secret APNS_KEY_P8 &&
    has_repo_secret APNS_TEAM_ID; then
    say "Apple APNs credentials already exist; leaving them unchanged."
  else
    step "As Account Holder or Admin, create a production APNs key for Yiru if one is unavailable."
    step "Download its .p8 file now; Apple only allows the private key to be downloaded once."
    ask APNS_KEY_ID "Paste the APNs Key ID:"
    ask APNS_TEAM_ID "Paste the 10-character Apple Team ID:"
    ask APNS_KEY_P8_PATH "Paste the path to the downloaded .p8 file:"
    if [[ ! -f "$APNS_KEY_P8_PATH" ]]; then
      warn "No APNs key file exists at that path."
      exit 1
    fi
    APNS_KEY_P8=$(<"$APNS_KEY_P8_PATH")
    set_secret APNS_KEY_ID "$APNS_KEY_ID"
    set_secret APNS_TEAM_ID "$APNS_TEAM_ID"
    set_secret APNS_KEY_P8 "$APNS_KEY_P8"
  fi

  if has_repo_secret GATEWAY_SHARED_SECRET; then
    say "GATEWAY_SHARED_SECRET already exists; leaving it unchanged."
  else
    GATEWAY_SHARED_SECRET=$(openssl rand -hex 32)
    set_secret GATEWAY_SHARED_SECRET "$GATEWAY_SHARED_SECRET"
    if command -v pbcopy >/dev/null 2>&1; then
      printf '%s' "$GATEWAY_SHARED_SECRET" | pbcopy
      note "The gateway token was copied to the clipboard; save it in your password manager now."
    else
      warn "The generated gateway token is stored in GitHub only; rotate it if the daemon needs a copy."
    fi
  fi
  set_var APNS_GATEWAY_ENABLED true
fi

finish
