import { cn } from '@/style/class-names'

export const styles = {
  container: cn('flex-1 bg-background'),
  header: cn('bg-background'),
  topBar: cn('flex-row items-center px-2 py-2 border-b border-b-border'),
  backButton: cn('p-1 rounded-none'),
  backButtonPressed: cn('bg-secondary'),
  backButtonPressedActive: cn('active:bg-secondary'),
  titleBlock: cn('flex-1 mx-2'),
  title: cn('text-foreground text-[18px] font-semibold'),
  meta: cn('text-muted-foreground text-[12px]'),
  refreshButton: cn('p-1 rounded-none'),
  refreshButtonPressed: cn('bg-secondary'),
  refreshButtonPressedActive: cn('active:bg-secondary'),
  scopeTabs: cn('flex-row px-3 pt-2 gap-1'),
  scopeTab: cn('flex-1 items-center py-2 rounded-none bg-card'),
  scopeTabActive: cn('bg-secondary'),
  scopeTabText: cn('text-muted-foreground text-[14px]'),
  scopeTabTextActive: cn('text-foreground font-semibold'),
  searchRow: cn('px-3 pt-2'),
  searchInput: cn('bg-card rounded-none px-3 py-2 text-foreground text-[14px]'),
  list: cn('px-3 pt-2 pb-6'),
  groupHeader: cn('flex-row items-center py-2 gap-2'),
  groupHeaderText: cn('text-muted-foreground text-[12px] font-semibold uppercase'),
  groupHeaderCount: cn('text-muted-foreground/60 text-[12px]'),
  card: cn('bg-card rounded-none p-3 mb-2'),
  cardPressed: cn('bg-secondary'),
  cardPressedActive: cn('active:bg-secondary'),
  cardTopRow: cn('flex-row items-center gap-2'),
  cardTitle: cn('flex-1 text-foreground text-[14px] font-semibold'),
  cardTimeAgo: cn('text-muted-foreground/60 text-[12px]'),
  cardLastMessage: cn('text-muted-foreground text-[12px] mt-1'),
  cardMetaRow: cn('flex-row items-center flex-wrap gap-2 mt-1'),
  cardMetaText: cn('text-muted-foreground/60 text-[12px]'),
  currentBadge: cn('bg-secondary rounded-none px-2 py-[2px]'),
  currentBadgeText: cn('text-primary text-[12px] font-semibold'),
  resumeButton: cn('min-h-7 min-w-7 items-center justify-center ml-auto px-1 py-1 rounded-none'),
  resumeButtonPressed: cn('opacity-[0.78]'),
  resumeButtonPressedActive: cn('active:opacity-[0.78]'),
  resumeButtonDisabled: cn('opacity-[0.45]'),
  preview: cn('mt-2 pt-2 border-t border-t-border gap-2'),
  previewTurn: cn('gap-[2px]'),
  previewRole: cn('text-muted-foreground/60 text-[12px] font-semibold uppercase'),
  previewText: cn('text-muted-foreground text-[12px]'),
  noticeBanner: cn('mx-3 mt-2 p-2 rounded-none bg-card'),
  noticeText: cn('text-amber-500 text-[12px]'),
  resumeBanner: cn('mx-3 mt-2 p-2 rounded-none bg-card'),
  resumeBannerText: cn('text-muted-foreground text-[12px]'),
  state: cn('flex-1 items-center justify-center p-6 gap-2'),
  stateTitle: cn('text-foreground text-[14px] font-semibold'),
  stateText: cn('text-muted-foreground text-[12px] text-center'),
  retryButton: cn('mt-2 px-4 py-2 rounded-none bg-secondary'),
  retryText: cn('text-foreground text-[14px] font-semibold')
} as const
