import type { RpcMethod } from '~main/runtime/rpc/core'

import { ORCHESTRATION_FEDERATION_ATTACH_METHODS } from './attach'
import { ORCHESTRATION_FEDERATION_CONTROL_METHODS } from './control'
import { ORCHESTRATION_FEDERATION_RELAY_METHODS } from './relay'

export const ORCHESTRATION_FEDERATION_METHODS: RpcMethod[] = [
  ...ORCHESTRATION_FEDERATION_ATTACH_METHODS,
  ...ORCHESTRATION_FEDERATION_RELAY_METHODS,
  ...ORCHESTRATION_FEDERATION_CONTROL_METHODS
]
